const brands = {
  '1800Contacts': { name: '1800Contacts', logo: '1800contacts.png' },
  'American Eagle': { name: 'American Eagle', logo: 'ae.png' },
  adidas: { name: 'adidas', logo: 'adidas.png' },
  BarkBox: { name: 'BarkBox', logo: 'barkbox.png' },
  Bloomingdales: { name: 'Bloomingdales', logo: 'bloomingdales.png' },
  Brandless: { name: 'Brandless', logo: 'brandless.png' },
  'Blue Apron': { name: 'Blue Apron', logo: 'blueapron.png' },
  Casper: { name: 'Casper', logo: 'casper.png' },
  'Charlotte Tilbury': { name: 'Charlotte Tilbury', logo: 'charlottetilbury.png' },
  CIBC: { name: 'CIBC', logo: 'cibc.png' },
  ClassPass: { name: 'ClassPass', logo: 'classpass.png' },
  Costco: { name: 'Costco', logo: 'costco.png' },
  'Draft Kings': { name: 'Draft Kings', logo: 'draft-kings.png' },
  Evernew: { name: 'Evernew', logo: 'evernew.png' },
  eBay: { name: 'eBay', logo: 'ebay.png' },
  FanXchange: { name: 'FanXchange', logo: 'fanxchange.png' },
  'Forever 21': { name: 'Forever 21', logo: 'forever21.png' },
  'Frank & Oak': { name: 'Frank & Oak', logo: 'frankandoak.png' },
  Gap: { name: 'Gap', logo: 'gap.png' },
  Groupon: { name: 'Groupon', logo: 'groupon.png' },
  'Happy Socks': { name: 'Happy Socks', logo: 'happysocks.png' }, 
  Hayneedle: { name: 'Hayneedle', logo: 'hayneedle.png' },
  'Hello Fresh': { name: 'HelloFresh', logo: 'hellofresh.png' }, 
  'H&R Block': { name: 'H&R Block', logo: 'hrblock.png' }, 
  'The Source': { name: 'The Source', logo: 'source.png' },
  Fabletics: { name: 'Fabletics', logo: 'fabletics.png' },
  Fitbit: { name: 'Fitbit', logo: 'fitbit.png' },
  Indigo: { name: 'Indigo', logo: 'indigo.png' },
  Jet: { name: 'Jet​.​com', logo: 'jet.png' },
  Koodo: { name: 'Koodo', logo: 'koodo.png' },
  Kobo: { name: 'Kobo', logo: 'kobo_us.png' },
  Koho: { name: 'Koho', logo: 'koho.png' },
  Lululemon: { name: 'Lululemon', logo: 'lululemon.png' },
  "Macy's": { name: "Macy's", logo: 'macys.png' },
  Mylo: { name: 'Mylo', logo: 'mylo.png' },
  'New Balance': { name: 'New Balance', logo: 'newbalance.png' },
  'Old Navy': { name: 'Old Navy', logo: 'oldnavy.png' },
  Petal: { name: 'Petal', logo: 'petal.png' },
  QVC: { name: 'QVC', logo: 'qvc.png' },
  Reebok: { name: 'Reebok', logo: 'reebok.png' },
  Sephora: { name: 'Sephora', logo: 'sephora.png' },
  "Sam's Club": { name: "Sam's Club", logo: 'samsclub.png' },
  Scotiabank: { name: 'Scotiabank', logo: 'scotiabank.png' },
  SoFi: { name: 'SoFi', logo: 'sofi.png' },
  Stash: { name: 'Stash', logo: 'stash.png' },
  "S'well": { name: "S'well", logo: 'swell.png' },
  Tatcha: { name: 'Tatcha', logo: 'tatcha.png' },
  "The Vitamin Shoppe": { name: "Vitamin Shoppe", logo: 'vitaminshoppe.png' },
  "Thrive Market": { name: "Thrive Market", logo: 'thrive.png' },
  Turbotax: { name: 'Turbotax', logo: 'turbotax.png' },
  Twine: { name: 'Twine', logo: 'twine.png' },
  'Uber Eats': { name: 'Uber Eats', logo: 'ubereats.png' },
  'Warby Parker': { name: 'Warby Parker', logo: 'warby.png' },
  Well: { name: 'Well.​ca', logo: 'well.png' },
}

export default brands
